//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_InternShip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBManagementEntities : DbContext
    {
        public DBManagementEntities()
            : base("name=DBManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANDTable> BRANDTables { get; set; }
        public virtual DbSet<CATEGORYTable> CATEGORYTables { get; set; }
        public virtual DbSet<PRODUCTTable> PRODUCTTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USERTABLE> USERTABLEs { get; set; }
    }
}
