//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT_InternShip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTTable
    {
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_IMAGE { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public Nullable<int> BRAND_ID { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
    
        public virtual BRANDTable BRANDTable { get; set; }
        public virtual CATEGORYTable CATEGORYTable { get; set; }
    }
}
